# Generated by Django 5.1.2 on 2025-04-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(' ', '  '), ('Fullstack_developer', 'Fullstack_developer'), ('manager', 'Manager'), ('Admin', 'Admin'), ('Associate', 'Associate'), ('intern', 'intern')], default='SBS_RESOURCE', max_length=20),
        ),
    ]
